// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTlCfcBXH_uWjDXUDSjqvk8Bsy-p8nTJA',
    appId: '1:391559773150:web:3aa8585600fd18a050bb4f',
    messagingSenderId: '391559773150',
    projectId: 'pos-system-lite',
    authDomain: 'pos-system-lite.firebaseapp.com',
    storageBucket: 'pos-system-lite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD7cJmyupz6wFMvmoNLtIio8e0pgFo__8',
    appId: '1:391559773150:android:572f43e88b76134d50bb4f',
    messagingSenderId: '391559773150',
    projectId: 'pos-system-lite',
    storageBucket: 'pos-system-lite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD23vd-3xiyvw3EfI6KT9mEq5U4a2KCyX4',
    appId: '1:391559773150:ios:db1c91e5fdbc416050bb4f',
    messagingSenderId: '391559773150',
    projectId: 'pos-system-lite',
    storageBucket: 'pos-system-lite.firebasestorage.app',
    iosBundleId: 'com.example.posSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD23vd-3xiyvw3EfI6KT9mEq5U4a2KCyX4',
    appId: '1:391559773150:ios:db1c91e5fdbc416050bb4f',
    messagingSenderId: '391559773150',
    projectId: 'pos-system-lite',
    storageBucket: 'pos-system-lite.firebasestorage.app',
    iosBundleId: 'com.example.posSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTlCfcBXH_uWjDXUDSjqvk8Bsy-p8nTJA',
    appId: '1:391559773150:web:1995a47609a4c4e450bb4f',
    messagingSenderId: '391559773150',
    projectId: 'pos-system-lite',
    authDomain: 'pos-system-lite.firebaseapp.com',
    storageBucket: 'pos-system-lite.firebasestorage.app',
  );
}